---
# tasks file for pbis
   - include: redhat.yml
     when: ansible_os_family == 'RedHat'

   - include: ubuntu.yml
     when: when: ansible_lsb.id == 'Ubuntu'


   - name: check the Domain status
     shell: /opt/pbis/bin/lsa get-status |grep Netbios |awk '{print $3}'
     register: domain_status


   - name: Join the machine if it is not already on the domain.
     command: /usr/bin/domainjoin-cli join internetq.corp {{ username }} {{password}}
     when: domain_status.stdout != "{{mydomain}}"
     notify:
          - config pbis shell
          - config pbis domain
